### PR TITLE
Add a TeV catalog

### PR DESCRIPTION
**Pull request by cdeil**
This PR is a step towards implementing  #22 , adding a TeV catalog.

Work in progress ... I'll try to add the Angular component now in this PR.

### CODE REVIEW

**Comment by cdeil** [comment]
@vorugantia - Can you have a look, please?

It might be best if you merge this and continue yourself, I'm not sure when I'll have time tomorrow yet.

Routing to a TeV source works, e.g.
http://localhost:4200/cat/tev/0

I didn't manage to add the TeV catalog to the select component, can you do this please?

**Comment by cdeil** [comment]
I also didn't try yet to add the TeV catalog to the map.

**Comment by vorugantia** [comment]
@cdeil - I'll take a look at code in the morning. Then I can merge and add TeV catalog to select and map. We should have a completed TeV catalog to present on Tuesday.

**Comment by vorugantia** [comment]
Code looks good. I'll merge and work on this.

**Pull request merged**
