### PR TITLE
Add images to surveys.ts

### PR DESCRIPTION
**Pull request by vorugantia**
These are the 7 surveys added in this PR, recommended by Nachi:
- [Planck R2 LFI](http://alasky.u-strasbg.fr/PLANCK/R2/LFI_Color_30_44_70)
- [Planck R1 HFI](http://alasky.u-strasbg.fr/PLANCK/HFIColor353-545-857)
- [Planck R2 HFI](http://alasky.u-strasbg.fr/PLANCK/R2/HFI_Color_353_545_857)
- [Spitzer's GLIMPSE360](http://www.spitzer.caltech.edu/glimpse360/aladin/data)
- [IRIS](http://cade.irap.omp.eu/documents/Ancillary/4Aladin/IRIS_4)
- [CGPS](http://cade.irap.omp.eu/documents/Ancillary/4Aladin/CGPS_VGPS_CONT/)
- [AKARI](http://cade.irap.omp.eu/documents/Ancillary/4Aladin/AKARI_WideS)

One more that Nachi recommended was [this Planck HFI image](http://irsa.ipac.caltech.edu/data/Planck/release_1/all-sky-maps/previews/HFI_SkyMap_857_2048_R1.10_nominal/index.html), but we would have to convert the FITS file to HiPS ourselves.

### CODE REVIEW

**Comment by cdeil** [comment]
> One more that Nachi recommended was this Planck HFI image, but we would have to convert the FITS file to HiPS ourselves.

Can you split this out into a separate reminder issue and milestone it as "whishlist"?

**Comment by cdeil** [comment]
👍 

I have two documentation requests:
1. for users, list the surveys we currently offer (with the link to CDS, as you did above) here:
   https://github.com/gammapy/gamma-sky/wiki/Datasets#images
   You could also point to the full list and say that suggestions for other surveys to include in that selection field are welcome.
2. for developers, leave a comment (maybe in that code file) how to obtain all this info for a given survey, so that I don't have to remember in case I want to add other surveys in the future.

```
  {
    "id": "P/Fermi/color",
    "url": "http://alasky.u-strasbg.fr/Fermi/Color",
    "name": "Fermi color",
    "maxOrder": 3,
    "frame": "equatorial",
    "format": "jpeg"
  },
```

**Comment by vorugantia** [comment]
Okay, I created the issue (I also just fixed the spelling on "wishlist" milestone). As for documentation requests:
1. Done. One thing is that for some of the links (e.g. the one for GLIMPSE360), the link appears dead when you click on it. But for some reason, Aladin Lite can still recognize them and load the images. I added this as a note.
2. Done in latest commit.

**Comment by cdeil** [comment]
👍 

The Planck one showing the gas is really nice!

I think we should mention some of the available images in the proceeding (of course stressing that these are just examples and 300+ are really available).
I'd even be in favour of adding a "table or available MWL images", so that people just skimming the writeup will notice it, or alternatively put a bullet list in the text to make it more visible.

**Comment by vorugantia** [comment]
I agree, it would definitely be good to mention available surveys.

I can't finish the proceeding draft today, but I can try to get it done tomorrow.

**Comment by cdeil** [comment]
No worries with the proceedings draft. We have to hand it in in October.

Just let me know whenever you have a first outline of contents and we'll start working on it any time.

**Pull request merged**
