### PR TITLE
Separate popup code from MapComponent

### PR DESCRIPTION
**Pull request by vorugantia**
I moved all of the popup code from MapComponent into a separate class Popup (in widgets folder). All of the popup code is still the same.

### CODE REVIEW

**Comment by cdeil** [comment]
👍 , it's a step in the right direction.

Do you want to merge it now, or go further in this PR?

One possible improvement would be to move `SNRcatUrl` to the SNR catalog class (the one that's independent of Angular).

**Comment by vorugantia** [comment]
I agree that the SNRcatUrl could be moved to its own class. I'll implement it tomorrow and then merge.

**Comment by cdeil** [comment]
I'm not saying you should do it here, because it's not high priority, but for the future: each catalog should have it's own popup component, where the html content is the template, and it contains a link "detail view" that takes one over to the source detail view.

**Comment by vorugantia** [comment]
Ok. added that in a Todo. I'll merge for now.

**Pull request merged**
