### PR TITLE
update Angular to 4.2.5

### PR DESCRIPTION
**Pull request by vorugantia**
@cdeil - I've updated the Angular packages to 4.2.5 and its dependencies in this PR. Can you please make sure you can run `npm start` successfully with this updated `package.json`?

### CODE REVIEW

**Comment by cdeil** [comment]
Is works for me locally.

I see a few deprecation warnings when I run `npm install`:
```
npm WARN deprecated ng2-bootstrap@1.6.3: DEPRECATED: package was renamed to ngx-bootstrap
npm WARN deprecated angular-cli@1.0.0-beta.26: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
```
https://gist.github.com/cdeil/031b9c5969d97170686cdc24b9b90549

When running `npm start` I see these deprecation warnings:
```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
```
https://gist.github.com/cdeil/d79afb29dcdd2a957796719731ddfaac

@vorugantia - Do you see the same warnings? Can you update the config or settings to get rid of them (i.e. follow the suggested changes from the warnings)

**Comment by vorugantia** [comment]
I think updating `angular-cli` does the trick:

```
$ npm uninstall --save-dev angular-cli
$ npm install --save-dev @angular/cli@latest
```

In the latest commit I also updated some other dependencies and packages for the project (rxjs, bootstrap, etc.) `npm install` and `npm start` should still be working.

**Comment by cdeil** [comment]
I still see this one warning:
```
$ time npm install
gamma-sky@0.3.0 /Users/deil/code/gamma-sky
├── @angular/animations@4.2.5 
├── UNMET PEER DEPENDENCY @angular/common@4.2.5
├── UNMET PEER DEPENDENCY @angular/core@4.2.5
├─┬ bootstrap@4.0.0-alpha.6 
│ ├── jquery@3.2.1 
│ └── tether@1.4.0 
├── ng2-select-compat@1.3.1 
├── ngx-bootstrap@1.7.1 
├── typescript@2.4.0  invalid
└── zone.js@0.8.12 

npm WARN ng2-select@1.2.0 requires a peer of @angular/common@^2.3.0 but none was installed.
npm WARN ng2-select@1.2.0 requires a peer of @angular/core@^2.3.0 but none was installed.
```
@vorugantia - Up to you if you want to fix this here or merge as-is.

Another thing you can do here or in a separate PR: please fix the CI build on travis-ci by editing the `.travis.yml` file in this repo and executing the correct commands.
See error here: https://travis-ci.org/gammapy/gamma-sky/builds/250370484#L2824

**Comment by vorugantia** [comment]
Yes, I forgot to mention - it appears they stopped updating `ng2-select` along with Angular, and so it can be updated no more than 1.2.0. There's nothing wrong with the implementation, as the messages are just warnings. I think for now it's okay to keep `ng2-select` running as it is because it's no problem from the user's side. Maybe later I will look for an alternative.

I'll work on the CI build in another PR.

**Comment by cdeil** [comment]
I think this is what the Google / Angular team has built, and are using themselves: https://material.angular.io/
So it's something that's well-done, -supported and -integrated with Angular.

OK to keep what we have now, but if you start changing things or looking for an alternative, I would suggest you look at Angular material first.

**Comment by vorugantia** [comment]
Merging this PR for now...

**Pull request merged**
